# -*- coding: utf-8 -*-
"""LLM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19H9kwkptpZXnVwvegZfSyCVQDoGzgvyt
"""

import spacy
import torch

import random
import requests

from collections import Counter

random_number = random.randint(1,50000)

target_text_url = "https://www.gutenberg.org/cache/epub/{}/pg{}.txt".format(random_number, random_number)

whole_text = requests.get(target_text_url)

nlp = spacy.load("en_core_web_sm")
document = nlp(whole_text.text)

print([(word.text, word.pos_) for word in document])

counted_words = Counter(document)

sorted(counted_words)